const artists = [
	{
		id: 1,
		name: "Errorr",
		tag: "fun",
		imgOne: "https://f4.bcbits.com/img/a1864420344_2.jpg",
		imgTwo: "https://post-punk.com/wp-content/uploads/2020/06/errorr_presspicture3-scaled.jpg",
		bio: `Errorr, is a band led by Swedish multi-instrumentalist, musician, and producer Leonard Kaage.  The band stylistically combines a wide range of rock-genres in their music but plays first and foremost both noise and punk rock.  Together, this three-piece creates a wall of sound with vigorous drumming, fuzz-drenched bass, and massive sounding guitars.  The songs are straightforward and direct but never seem to be predictable.`,
		embed: "https://www.youtube.com/embed/UmUO503RdmE",
		facebook: "",
		instagram: "",
		youtube: "",
		bandcamp: "",
	},
	{
		id: 2,
		name: "Haus Band",
		tag: "site",
		imgOne: "https://f4.bcbits.com/img/a4029138062_16.jpg",
		imgTwo: "https://townsquare.media/site/838/files/2021/05/hausband.jpeg?w=980&q=75",
		bio: "It’s been an interesting few months for Eddie Argos, illustrious front man of sardonic indie art pioneers Art Brut. In echoes of that seminal hit, he’s only gone and ‘Formed A Band’ look at him, he’s formed a band!…a Bob Dylan covers band at that – with fellow Berlin artist’s Olga Karatzioti-B. and Leonard Kaage of Errorr and The Underground Youth fame. “I’ve always wanted to make a Dylan covers album,” says an enthusiastic Argos, “but the opportunity really came up when, during Lockdown, I heard my neighbours practicing their songs through the floor, and thought to myself ‘they sound like they need a singing partner‘. I’d heard them practicing Pixies the week before so I knew they were awesome dudes. We’d also been looking after each other‘s cats.”",
		embed: "https://www.youtube.com/embed/UmUO503RdmE",
		facebook: "",
		instagram: "",
		youtube: "",
		bandcamp: "",
	},
	{
		id: 3,
		name: "San Marino",
		tag: "site",
		imgOne: "https://f4.bcbits.com/img/a0551211661_2.jpg",
		imgTwo: "https://post-punk.com/wp-content/uploads/2020/06/errorr_presspicture3-scaled.jpg",
		bio: "Errorr, is a band led by Swedish multi-instrumentalist, musician, and producer Leonard Kaage. The band stylistically combines a wide range of rock-genres in their music but plays first and foremost both noise and punk rock.Together, this three-piece creates a wall of sound with vigorous drumming, fuzz-drenched bass, and massive sounding guitars. The songs are straightforward and direct but never seem to be predictable.",
		embed: "https://www.youtube.com/embed/UmUO503RdmE",
		facebook: "",
		instagram: "",
		youtube: "",
		bandcamp: "",
	},
	{
		id: 4,
		name: "Camel Moon",
		tag: "site",
		imgOne: "https://f4.bcbits.com/img/a4245655642_2.jpg",
		imgTwo: "https://post-punk.com/wp-content/uploads/2020/06/errorr_presspicture3-scaled.jpg",
		bio: "Errorr, is a band led by Swedish multi-instrumentalist, musician, and producer Leonard Kaage. The band stylistically combines a wide range of rock-genres in their music but plays first and foremost both noise and punk rock.Together, this three-piece creates a wall of sound with vigorous drumming, fuzz-drenched bass, and massive sounding guitars. The songs are straightforward and direct but never seem to be predictable.",
		embed: "https://www.youtube.com/embed/UmUO503RdmE",
		facebook: "",
		instagram: "",
		youtube: "",
		bandcamp: "",
	},
	{
		id: 4,
		name: "Niko Novak",
		tag: "site",
		imgOne: "https://f4.bcbits.com/img/a3959237677_16.jpg",
		imgTwo: "https://post-punk.com/wp-content/uploads/2020/06/errorr_presspicture3-scaled.jpg",
		bio: "Errorr, is a band led by Swedish multi-instrumentalist, musician, and producer Leonard Kaage. The band stylistically combines a wide range of rock-genres in their music but plays first and foremost both noise and punk rock.Together, this three-piece creates a wall of sound with vigorous drumming, fuzz-drenched bass, and massive sounding guitars. The songs are straightforward and direct but never seem to be predictable.",
		embed: "https://www.youtube.com/embed/UmUO503RdmE",
		facebook: "",
		instagram: "",
		youtube: "",
		bandcamp: "",
	},
];
export default artists;
