const releases = [
	{
		id: 1,
		artist: "Haus Band",
		title: "She Belongs to Me",
		image: "https://f4.bcbits.com/img/a4029138062_2.jpg",
		info: "",
	},
	{
		id: 2,
		artist: "San Marino",
		title: "San Marino (EP)",
		image: "https://f4.bcbits.com/img/a0551211661_2.jpg",
		info: "",
	},
	{
		id: 3,
		artist: "San Marino",
		title: "Take Me to Rome",
		image: "https://f4.bcbits.com/img/a1027387481_2.jpg",
		info: "",
	},
	{
		id: 4,
		artist: "Camel Moon",
		title: "The World Doesn't Need You Anyway",
		image: "https://f4.bcbits.com/img/a4245655642_2.jpg ",
		info: "",
	},
	{
		id: 5,
		artist: "Errorr",
		title: "Repeater",
		image: "https://f4.bcbits.com/img/a1864420344_2.jpg",
		info: "",
	},
	{
		id: 6,
		artist: "San Marino",
		title: "Doppelgänger",
		image: "https://f4.bcbits.com/img/a1827182133_2.jpg",
		info: "",
	},
	{
		id: 7,
		artist: "Niko Novak",
		title: "Tuesdays, Thursdays, Saturdays",
		image: "https://f4.bcbits.com/img/a3959237677_2.jpg",
		info: "",
	},
	{
		id: 8,
		artist: "Errorr",
		title: "Fuzzy",
		image: "https://f4.bcbits.com/img/a4074180445_2.jpg",
		info: "",
	},
	{
		id: 9,
		artist: "Errorr",
		title: "Perfect Example",
		image: "https://f4.bcbits.com/img/a0267718120_2.jpg",
		info: "",
	},
	{
		id: 10,
		artist: "Niko Novak",
		title: "DNA",
		image: "https://f4.bcbits.com/img/a2592343655_2.jpg",
		info: "",
	},
	{
		id: 11,
		artist: "Errorr",
		title: "Wrong Direction",
		image: "https://f4.bcbits.com/img/a3940677445_2.jpg",
		info: "",
	},
	{
		id: 12,
		artist: "Errorr",
		title: "Smash Hit",
		image: "https://f4.bcbits.com/img/a3940677445_2.jpg",
		info: "",
	},
];
export default releases;
